version: '2'
jobs:
  build:
    working_directory: ~/receiver
    machine: true
    steps:
      - checkout
      - run:
          name: check docker version
          command: |
            docker version
            docker-compose version
      - run:
          name: build docker
          command: |
            docker-compose build
            docker-compose up -d
      - run:
          name: test
          command: |
            docker-compose run app go test -cover ./...
